 # mysql.yaml
- name: configure mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root password # setting up the root password for mysql
    ansible.builtin.command: mysql_secure_installation --set-root-passwd 'Roboshop@1' # here we are using command module because we don't have any module in ansible for mysql_secure_installation
      