
#  Configure RabbitMQ Component
- name: setup rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repo.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.dnf:
       name: rabbitmq-server
       state: started
       enable: yes

  - name: create rabbitmq user
    community.rabbitmq_user:
       user: roboshop
       password: roboshop123
       permissions:
          - vhost: /
            configure_priv: . *
            read_priv: .*
            write_priv: .*
       state: present                                                