# Configure Shipping Component
- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql # shipping component is a java based application so we need to install maven and mysql client
    ansible.builtin.dnf:
      name: "{{ item }}" # here i used loop to install multiple packages
      state: installed
    loop: # list of packages to be installed
    - maven
    - mysql
    
  - name: install PyMySQL and cryptography  # shipping component is a python based application so we need to install python3.9 and pip3.9
    ansible.builtin.pip:
      name: "{{ item }}" # here i used loop to install multiple python packages
      executable: pip3.9  # here we are using pip3.9 because it is python dependiency 
    loop:
    - cryptography # cryptography is a python package to encrypt the data
    - PyMySQL # PyMySQL is a python package to connect to mysql database

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: extract shipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  # - name: connect to mysql using app user
  #   community.mysql.mysql_info:
  #     login_user: shipping
  #     login_password: RoboShop@1
  #     login_host: mysql.daws84s.site
  #     login_db: cities

  - name: import data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.daws84s.site
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping
  


  
